apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: team-dev-alert
  namespace: team-fluxcicd
spec:
  providerRef:
    name: pagerduty3
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: team-dev-apps
