apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml


# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   # - cert-manager/flux-kustomize.yaml
#   # - ingress-nginx/flux-kustomize.yaml
#   # - monitoring/flux-kustomize.yaml
#   - ../../tenants/team-one
#   - ../../tenants/team-two
#   - gotk-components.yaml
#   - gotk-sync.yaml
