apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: team-two-pagerduty
  namespace: team-two-webapp
spec:
  type: pagerduty
  address: https://events.pagerduty.com/v2/enqueue
  channel: ad1e1b04a5264506c071008031e1f38f
  # secretRef:
  #   name: pagerduty-secret