apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              static_configs:
                - targets: ['0.0.0.0:8888']

      filelog:
        # include: [ "/var/log/containers/*.log" ]
        include: [ "/var/log/app.log"]  
        start_at: beginning
        operators:
          - type: json_parser
            id: parse-logs
            field: body

    processors:
      batch:
      attributes:
        actions:
          - action: insert
            key: tenant
            from_attribute: k8s.namespace.name

    exporters:
      prometheusremotewrite:
        endpoint: http://prometheus.default.svc.cluster.local:9090/api/v1/write
        tls:
          insecure_skip_verify: true
      loki:
        endpoint: http://loki.default.svc.cluster.local:3100/loki/api/v1/push
      otlp:
        endpoint: tempo.default.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch, attributes]
          exporters: [prometheusremotewrite]

        logs:
          receivers: [filelog, otlp]
          processors: [batch, attributes]
          exporters: [loki]

        traces:
          receivers: [otlp]
          processors: [batch, attributes]
          exporters: [otlp]

