apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
 name: team-two-rocketchat
 namespace: team-two-webapp
spec:
 type: rocket
 channel: "#team-two"
 address: http://10.80.3.54:3000/hooks/6809eaec238490d4fdaef1bf/2TKwt8Md7qPvtmDwdBFTsnwQkZPm8s9H3YJjzxCZTw6pYqBy